### ISSUE TITLE
Python 2to3

### ISSUE THREAD

**Issue by satreix** [liluo/mime#2]
Would it be possible to update this package to **work with python3** ?

I tried to fork & fix it (`satreix/mime`) but had issues with `cmp` function that has been removed in py3.

I am trying to get your python version of linguist to work with python3.
I did a small fix on `liluo/pygments-github-lexers` and your mime package is the next one failing.

**Comment by liluo** [comment]
@xtao pls see this.

**Comment by xtao** [comment]
:beers:

**Comment by satreix** [comment]
Do you want to keep the package working on py2 & py3 or is it ok to drop py2 support?
I'm trying to fix it on my own but can get it to pass the tests :worried:.

**Comment by satreix** [comment]
For now I still have a few test failing: https://travis-ci.org/satreix/mime/jobs/47439862
Do you have an idea on how to fix those `cmp` errors?

**Comment by liluo** [comment]
@satreix 

> Do you want to keep the package working on py2 & py3 or is it ok to drop py2 support?

py2 & py3

**Comment by thundergolfer** [comment]
I am also interested in this working for py3. Like @satreix, I am tring to python linguist working with python3

**Comment by satreix** [comment]
@liluo @xtao are you still working on this? How can I help make it happen?
