### ISSUE TITLE
Porting to Python3 - How is Types() initialized

### ISSUE THREAD

**Issue by thundergolfer** [liluo/mime#3]
I am working on getting this package to support Python 2 and Python 3 code, but I am stuck on something. 

The `Types()` class appears to be 'initialized' by the `MimeTypes()` class in `mime_types.py` on import. I do not know how this works and it doesn't work on Python 3. 

Attempting to access `Types.type_veriants` dictionary in Python 3 just returns None for all Mimetypes. The dictionary is empty. However in Python 2 the import initializes the `Types()` class correctly and the code functions. 

How is it that simply importing `Type` and `Types` from the `mime` package initializes the `Types()` class by running the `load_from_file()` class method?

**Comment by thundergolfer** [comment]
I have figured this out, and have now implemented python 3 support, see #4

**Comment by liluo** [comment]
👍
